### ISSUE TITLE
This be an issue I created 

### ISSUE THREAD

**Issue by fiona127** [AUP-SE/kiwi#4]
Xaviera can u edit this and therefore post ur issue?

**Comment by areivaX** [comment]
yep but I wanted to post an issue in the AUP-SE issues thingy, not just in kiwi

**Comment by areivaX** [comment]
but whatever I'll put it here and then show it to prof tomorrow

**Comment by areivaX** [comment]
xavxav:~/workspace/kiwi (newCourseMaybe) $ rails generate migration createCourses
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych.rb:377:in `parse': (<unknown>): could not find expected ':' while scanning a simple key at line 14 column 1 (Psych::SyntaxError)
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych.rb:377:in`parse_stream'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych.rb:325:in `parse'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych.rb:252:in`load'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:391:in `secrets'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:178:in`key_generator'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:206:in `message_verifier'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/globalid-0.3.7/lib/global_id/railtie.rb:25:in`block (2 levels) in class:Railtie'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/lazy_load_hooks.rb:45:in`block in run_load_hooks'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/lazy_load_hooks.rb:44:in `each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/lazy_load_hooks.rb:44:in`run_load_hooks'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in`instance_exec'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in`block in run_initializers'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:350:in`block (2 levels) in each_strongly_connected_component'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:349:in`block in each_strongly_connected_component'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in`call'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:226:in`tsort_each'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in`run_initializers'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
        from /home/ubuntu/workspace/kiwi/config/environment.rb:5:in`<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/application.rb:92:in `require'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/application.rb:92:in`preload'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/application.rb:143:in `serve'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/application.rb:131:in`block in run'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/application.rb:125:in `loop'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/application.rb:125:in`run'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in`require'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in`<main>'
xavxav:~/workspace/kiwi (newCourseMaybe) $ 
xavxav:~/workspace/kiwi (newCourseMaybe) $ rake routes
rake aborted!
Psych::SyntaxError: (<unknown>): could not find expected ':' while scanning a simple key at line 14 column 1
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:391:in `secrets'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:178:in`key_generator'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:206:in `message_verifier'
/usr/local/rvm/gems/ruby-2.3.0/gems/globalid-0.3.7/lib/global_id/railtie.rb:25:in`block (2 levels) in class:Railtie'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/lazy_load_hooks.rb:45:in`block in run_load_hooks'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/lazy_load_hooks.rb:44:in `each'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/lazy_load_hooks.rb:44:in`run_load_hooks'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in`instance_exec'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in`block in run_initializers'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:352:in`initialize!'
/home/ubuntu/workspace/kiwi/config/environment.rb:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:328:in`require'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:328:in `require_environment!'
/usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:457:in`block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in`eval'
/usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => routes => environment
(See full trace by running task with --trace)

**Comment by areivaX** [comment]
just wanted to save this error. got it a couple different times trying to do "rails generate migration someCourses"; thought it might be an issue with my branch which I awkwardly rebased, so I switched back to master and created a fresh branch off of it, but still got the same error. I get it when I try to do rake routes as well soooo noiciice.

update: same damn thing happens if I try to run cucumber or whatever, amazing
